"""
Data Models and Type Definitions
================================

All dataclasses and enums used throughout TriMedAgent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from PIL import Image


# =============================================================================
# Enums
# =============================================================================

class Strategy(Enum):
    """Detection strategy based on target size."""
    GLOBAL_SCAN = "global_scan"      # Full image scan for large objects
    ZOOM_IN = "zoom_in"              # Crop region first for small objects
    MULTI_SCALE = "multi_scale"      # Try multiple scales
    SLIDING_WINDOW = "sliding_window" # Grid-based scanning


class TargetSize(Enum):
    """Expected size of target pathology."""
    TINY = "tiny"        # < 5% of image (nodules, calcifications)
    SMALL = "small"      # 5-15% (lesions, small tumors)
    MEDIUM = "medium"    # 15-30% (organs, larger tumors)
    LARGE = "large"      # > 30% (full organs, diffuse patterns)


# =============================================================================
# Planning Data Classes
# =============================================================================

@dataclass
class StrategicPlan:
    """Strategic plan generated by LLaVA Planner."""
    target_object: str = ""           # What to find (e.g., "nodule", "tumor")
    target_size: TargetSize = TargetSize.MEDIUM
    anatomical_location: str = ""     # Where to look (e.g., "right_upper_lobe")
    strategy: Strategy = Strategy.GLOBAL_SCAN
    detection_prompt: str = ""        # Prompt for DINO
    confidence_threshold: float = 0.25
    max_detections: int = 10
    reasoning: str = ""               # LLaVA's reasoning
    fallback_regions: List[str] = field(default_factory=list)


# =============================================================================
# Detection Data Classes
# =============================================================================

@dataclass
class DetectionResult:
    """Result from a single detection attempt."""
    boxes: List[List[float]] = field(default_factory=list)
    scores: List[float] = field(default_factory=list)
    phrases: List[str] = field(default_factory=list)
    source_region: str = "full"       # Which region was scanned
    crop_offset: Tuple[int, int] = (0, 0)  # Offset for coordinate mapping
    crop_scale: Tuple[float, float] = (1.0, 1.0)  # Scale for coordinate mapping
    is_valid: bool = True
    rejection_reason: str = ""


@dataclass
class VerificationResult:
    """Result from verification step."""
    is_valid: bool = True
    confidence: str = "high"          # high, medium, low
    explanation: str = ""
    suggested_action: str = ""        # accept, reject, retry_with_zoom


# =============================================================================
# Agent State
# =============================================================================

@dataclass
class AgentState:
    """Current state of the ReAct agent."""
    iteration: int = 0
    max_iterations: int = 3
    plan: Optional[StrategicPlan] = None
    detections: List[DetectionResult] = field(default_factory=list)
    verified_boxes: List[List[float]] = field(default_factory=list)
    masks: List[Any] = field(default_factory=list)
    action_history: List[str] = field(default_factory=list)
    thought_history: List[str] = field(default_factory=list)
    success: bool = False


# =============================================================================
# Pipeline Results
# =============================================================================

@dataclass
class TriageResult:
    """Result from BiomedCLIP triage."""
    modality: str = ""
    modality_confidence: float = 0.0
    abnormality: str = ""
    abnormality_confidence: float = 0.0
    all_scores: Dict[str, float] = field(default_factory=dict)


@dataclass
class RAGResult:
    """Result from RAG query."""
    answer: str = ""
    sources: List[str] = field(default_factory=list)
    confidence: float = 0.0
    query: str = ""


@dataclass
class PipelineResult:
    """Final pipeline result."""
    # Triage
    triage_modality: str = ""
    triage_confidence: float = 0.0
    
    # Planning
    strategic_plan: Optional[StrategicPlan] = None
    
    # Detection
    raw_boxes: List[List[float]] = field(default_factory=list)
    verified_boxes: List[List[float]] = field(default_factory=list)
    detection_scores: List[float] = field(default_factory=list)
    
    # Segmentation
    masks: List[Any] = field(default_factory=list)
    
    # Analysis
    llava_analysis: str = ""
    final_report: str = ""
    rag_response: str = ""
    
    # Visualization
    annotated_image: Optional[Image.Image] = None
    
    # Metadata
    execution_time: float = 0.0
    steps_executed: List[str] = field(default_factory=list)
    agent_iterations: int = 0
    errors: List[str] = field(default_factory=list)
    success: bool = True
